### ISSUE TITLE
Make it possible to build netboot images

### ISSUE THREAD

**Issue by mikn** [Webconverger/webc#103]
The current customisations to support git-fs seems to be blocking netboot builds, would be nice if provisions could be made to support netboot builds too!

**Comment by kaihendry** [comment]
I am not going to support netboot style deployment. I think it's fairly fast and straightforward to deploy by USB stick. We also have working hdd images which probably will suffice for people absolutely need netboot. :grimacing:

**Comment by stridger** [comment]
That's a shame, and unfortunately made us move to Internet Web Kiosk even though we would have preferred Webconverger. But running around with USB sticks and climbing up ladders to get to our 8 noticeboard mini PCs is simply not an option...

**Comment by kaihendry** [comment]
Hmmm, have you tried this option? This was user contributed: https://webconverger.org/pxeboot/

Surely there is a Webconverger independent method of imaging a hard drive via netboo, with Webconverger. Does that make sense?

**Comment by stridger** [comment]
Thanks :)

Imaging - yes. But imaging is pretty clunky for a kiosk, it does require console access/interaction for the initial imaging process and it then runs on the local disks which are prone to failure. True PXE booting would allow the machines to be completely diskless, you just set them to boot from the network, specify any configuration parameters as kernel options in PXELinux and it just starts up without any interaction. For an update all one would need to do is reboot. Seems like the best option in large scale environments and used to be very easy with SquashFS. Not sure if anybody found a solution for GitFS yet, but I couldn't get it to work when I tried a year or so ago.

**Comment by kaihendry** [comment]
Oh I understand you a bit better now. Tbh the real reason is that no client asked for that work and of course I can't afford to spend time on features no one is going to pay for. I am confident I could come up with something if there was 8 machines on annual subscription!

**Comment by stridger** [comment]
Thanks :) Had we known it back then, then paying for it would have been a real option, unfortunately I have now done all the work with IWK and it does what we need with PXE etc, so I couldn't justify the (internal and external) cost of switching at this stage, I'm afraid. We may well come back at some point in the future though when reviewing the system again. Many thanks for looking at this though and all the best with the project, which seems like an excellent software bundle!

**Comment by kaihendry** [comment]
Ok, np. Isn't IWK horribly out of date? Or does it update? I'm not sure...
