### ISSUE TITLE
Audio issues

### ISSUE THREAD

**Issue by dittaeva** [Webconverger/webc#192]
On my Dell laptop sound works when you start the machine, but it seems to only work for one application, and then stops working. Let's say you first visit youtube.com where it work, and then visit grooveshark.com, where it will not work. Seems to be independent of Flash.

I also just upgraded from a 2-3 years old Webconverger on two old HP Compaq (Pentium 4 HT) desktop computers, where there is no sound at all.

**Comment by thatvideowebguy** [comment]
Hi, I've an  audio issues to on my Nuc, The sound out from sound card (jack) not to hdmi ?
Is it possible to configure the audio output method from config web interface ?

**Comment by kaihendry** [comment]
Are you using the latest Jessie based build? http://build.webconverger.org/ Or what is the version?

There is no interface to pulseaudio atm, I generally try to make sure all outputs have sensible defaults.

**Comment by kaihendry** [comment]
Care to please reproduce in http://build.webconverger.org/latest.iso ? Else I may close the bug. Thank you!

**Comment by dittaeva** [comment]
Don't have time, sorry.
