### ISSUE TITLE
Time not synced

### ISSUE THREAD

**Issue by dittaeva** [Webconverger/webc#194]
I've had configuration activation fail on two machines now, and it seems to be because the time on the machines isn't updated (ntd). The problem has manifested itself on two different networks.

Latest example is with id C62BCE60-AC90-11DC-A70E-00A0D1A300D4;00:a0:d1:a3:00:d4
I've added support to the config, but the logs seems to take some time to appear on the support page.

**Comment by kaihendry** [comment]
Trying to come up with a NTP fallback https://lists.freedesktop.org/archives/systemd-devel/2016-June/036975.html
