### ISSUE TITLE
Enable Firefox Hello with boot argument

### ISSUE THREAD

**Issue by dittaeva** [Webconverger/webc#213]
[Firefox Hello](https://support.mozilla.org/en-US/kb/firefox-hello-video-and-voice-conversations-online) seems to be a very promising technology for video telephony/conferencing, but to use it in Firefox [the button for it needs to be enabled](https://support.mozilla.org/en-US/kb/where-firefox-hello-button), and [there might be extra settings that need enabling on debian](https://twitter.com/schiessle/status/541375731117621250).

I think video conferencing terminal could be a use case for Webconverger, and thus an API argument for it could be warranted with the next release using Firefox 35.

**Comment by kaihendry** [comment]
Yes, the [hello button](https://support.mozilla.org/en-US/kb/where-firefox-hello-button) is hidden in my tests. IIUC there is no keyboard shortcut.

I can however join a Hello conversation IIUC by following a URL? e.g. https://hello.firefox.com/Ucov22K4-K0

<img src=http://s.natalian.org/2015-01-16/firefox-hello-test.png>

So it doesn't have to be explicitly enabled in the UI, does it now?

Any thoughts @mkaply ?


Btw I've never got it to work yet. Always says "already two people in the conversation" room when I try to join. :(

**Comment by dittaeva** [comment]
What I'm asking for is for the button to be enabled so that Webconverger could be used to make a "Firefox Hello terminal" also for calling people up with Firefox Hello.

[Did you read the tweet I linked to](https://twitter.com/schiessle/status/541375731117621250)? Apparently "you need to enable it explicitly by setting "loop.throttled" to "false" in about:config".

The service/feature does seem to be unstable though, and is in beta, so I suppose supporting/implementing this isn't at all urgent.

**Comment by kaihendry** [comment]
OK, IIUC you want the button to initiate calls. Hmmm, I don't see why this can't be done via a Web app instead of a dedicated chrome UI addition.

Not sure about this loop throttled stuff, though you could experiment yourself via the `prefs=` API.

e.g. prefs=http://prefs.webconverger.com/2015/disable-pdfjs.js

No hurry. :-)

**Comment by dittaeva** [comment]
Looks like [the throttle setting is only used for a gradual introduction of Firefox Hello, and will be removed entirely in FF36](https://bugzilla.mozilla.org/show_bug.cgi?id=1073215).

WebRTC can be used via a web app, but can you easily interact with Firefox Hello using a web app? I'll try setting the loop.throttle setting (to false), but from what I understand, any new button will have to be "a dedicated chrome UI addition" so it will most likely have no effect.

**Comment by kaihendry** [comment]
Why not just use http://getaroom.io/?

I don't see the point of having dedicated Chrome UI to favour one of many WebRTC services.

**Comment by dittaeva** [comment]
Indeed, thanks for the link.
