### ISSUE TITLE
i3/i5/i7 6th generation (Skylake) NUCs have unsupported i219V Ethernet

### ISSUE THREAD

**Issue by n2qcn** [Webconverger/webc#227]
i3/i5/i7 6th generation (Skylake) from Intel (NUC) and Gigabyte (BRIX) use the 100 Series PCH (Sunrise Point) {embedded in the case of the NUCs} that have an internal i219V ethernet. Webconverger 34 (Nice!) has a /lib/modules/$(uname -r)/kernel/drivers/net/ethernet/intel/e1000e/e1000e.ko version of 2.3.2-k and 3.3.3 can be found http://www.intel.com/content/www/us/en/support/network-and-i-o/ethernet-products/000005480.html and would be a nice addition to the next iso. :-)

**Comment by kaihendry** [comment]
Hey, thanks for that info. I want some Skylake hardware !! ;)

I just noticed on my cutting edge (Arch) dev machine I'm only rocking 3.2.6. http://s.natalian.org/2016-02-23/4.4.1-e1000e.txt

I prefer to use stock kernels from Debian so obviously there is some lag here. Could you do me a favour a file a bug on Debian stable?

**Comment by n2qcn** [comment]
Well, it is kinda newish 
https://build.opensuse.org/package/view_file/hardware/intel-e1000e/intel-e1000e.changes
http://download.opensuse.org/repositories/hardware/openSUSE_13.2/x86_64/intel-e1000e-kmp-default-3.3.3_k3.16.6_2-1.1.x86_64.rpm

**Comment by kaihendry** [comment]
Could you please email me @n2qcn ... would like to chat more about NUCs to you since you seem to know more about them than I do. ;)

**Comment by n2qcn** [comment]
i219LM works with the current images.
